apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web # Linked with `labels` of other congigs. the `component` is arbitrary too
  ports:
    - port: 3000 # To be accessed by other pods
      targetPort: 3000 # Links to the `component: web` pod (`containerPort`)