apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres # Linked with `labels` of other congigs. the `component` is arbitrary too
  ports:
    - port: 5432 # To be accessed by other pods
      targetPort: 5432 # Links to the `component: web` pod (`containerPort`)