apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis # Linked with `labels` of other congigs. the `component` is arbitrary too
  ports:
    - port: 6379 # To be accessed by other pods
      targetPort: 6379 # Links to the `component: web` pod (`containerPort`)