apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server # Linked with `labels` of other congigs. the `component` is arbitrary too
  ports:
    - port: 5000 # To be accessed by other pods
      targetPort: 5000 # Links to the `component: web` pod (`containerPort`)